# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test

on:
  #  push:
  #    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: リポジトリチェックアウト
        uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node-version }} セットアップ
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: パッケージインストール
        run: yarn install

      - name: firebase-toolsをインストール
        run: yarn add firebase-tools

      - name: エミュレータの起動
        run: yarn emulators:start &

      - name: エミュレータの起動待機...
        run: sleep 10

      - name: テスト実行
        run: yarn test

      - name: エミュレータのレポート待機...
        run: sleep 10

      - name: coverage request
        id: coverageRequest
        uses: SonicGarden/firestore-rules-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report-url: "http://localhost:8080/emulator/v1/projects/fs-sample-open-chat-test:ruleCoverage"
